### ISSUE TITLE
Adding new video into training data

### ISSUE THREAD

**Issue by jayneeee** [huguesvinzant/Motion-Correction#1]
Hi, I'm currently trying to run the model for my personal project. I would like to know if I want to add new video with different action, where and how can I add it for training? I'm aware that the 'Data' folder is where we put our test video, isit possible for me to add new videos for training a new label? 

We may discuss over mail since this is not an issue with the package. :)

**Comment by huguesvinzant** [comment]
Hi, can you specify what part of the project you want to train for new labels? If it's the pose estimation itself you should refer to [the work of mkocabas](https://github.com/mkocabas/VIBE). If however you just want to tune the motion correction then what I suggest is to first extract the 3D poses and labels and then add this information in [this file](https://github.com/huguesvinzant/Motion-Correction/blob/master/PoseCorrection/Data/010920/data_3D.pickle) using the same format.

I'm closing the issue but do not hesitate to reach by email.
